<a href="https://colab.research.google.com/github/AneshkaGoyal/SentimentalAnalysis/blob/master/SentimentPred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import numpy as np

# read data from text files
with open('/content/sample_data/reviews.txt', 'r') as f:
    reviews = f.read()
with open('/content/sample_data/label.txt', 'r') as f:
    labels = f.read()


In [93]:
print(reviews[:2000])
print(type(reviews))
#all_text=''.join(reviews)
#print(all_text)


bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

In [94]:
print(labels[:20])

positive
negative
po


In [95]:
from string import punctuation

In [ ]:
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [96]:
print(type(reviews))
reviews = reviews.lower() # lowercase, standardize
all_text = ''.join([c for c in reviews if c not in punctuation])

# split by new lines and spaces
reviews_split = all_text.split('\n')
all_text = ' '.join(reviews_split)

# create a list of words
words = all_text.split()

<class 'str'>


In [97]:
words[:10]

['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the']

In [98]:
from collections import Counter

## Build a dictionary that maps words to integers
counts = Counter(words)
print((counts.get))
vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

## use the dict to tokenize each review in reviews_split
## store the tokenized reviews in reviews_ints
reviews_ints = []
for review in reviews_split:
    reviews_ints.append([vocab_to_int[word] for word in review.split()])

<built-in method get of Counter object at 0x7f36151c1f10>


In [107]:
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:2])
reviews_ints = reviews_ints[:25000][:]

Unique words:  74245

Tokenized review: 
 [[30645, 297, 6, 3, 1046, 210, 8, 2144, 32, 1, 171, 59, 15, 49, 83, 6026, 44, 365, 108, 141, 15, 6201, 60, 155, 9, 1, 5023, 5956, 475, 70, 5, 263, 12, 30645, 297, 13, 1893, 6, 74, 2326, 5, 621, 73, 6, 6201, 1, 25884, 5, 2038, 11324, 1, 5809, 1448, 36, 51, 66, 203, 142, 67, 1188, 6201, 20985, 1, 58621, 4, 1, 220, 907, 31, 2969, 70, 4, 1, 5580, 10, 670, 2, 67, 1448, 52, 10, 216, 1, 406, 9, 62, 3, 1414, 3573, 782, 5, 3520, 182, 1, 365, 10, 1228, 13377, 32, 297, 3, 342, 345, 2822, 10, 143, 127, 5, 7681, 30, 4, 130, 6201, 1414, 2300, 5, 30645, 297, 10, 524, 12, 109, 1434, 4, 60, 528, 102, 12, 30645, 297, 6, 225, 4185, 48, 3, 2187, 12, 8, 205, 23], [63, 4, 3, 122, 36, 47, 6994, 1437, 16, 3, 4657, 504, 45, 18, 3, 622, 133, 12, 6, 3, 1284, 463, 4, 1716, 210, 3, 10926, 6916, 308, 6, 679, 81, 35, 1968, 1071, 2912, 34, 1, 913, 72393, 4, 8, 13, 4874, 455, 8, 2647, 1716, 1, 220, 59, 18, 58, 806, 1239, 823, 229, 8, 43, 98, 123, 1426, 57, 147, 38, 1, 968, 144

In [100]:
# 1=positive, 0=negative label conversion
labels_split = labels.split('\n')
encoded = np.array([1 if label == 'positive' else 0 for label in labels_split])

In [108]:
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 0
Maximum review length: 2514


In [109]:
print('Number of reviews before removing outliers: ', len(reviews_ints))

## remove any reviews/labels with zero length from the reviews_ints list.
l=[]

reviews_ints = [r if len(r)>0 else l.append(ii) for ii,r in enumerate(reviews_ints) ]
encoded_labels = []
for i in l:
  encoded.pop(i)
for e in encoded:
  encoded_labels.append(e) 
print(encoded_labels)
print(len(encoded)==len(encoded_labels))
encoded_labels = np.array(encoded_labels)
print(l)




print('Number of reviews after removing outliers: ', len(reviews_ints))

Number of reviews before removing outliers:  25000
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 

In [110]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    ## implement function
    features = []
    for i,r in enumerate(reviews_ints):
      if(len(r)>seq_length):
        r = r[:seq_length]
        
      elif(len(r)<seq_length):
        shape_refined = seq_length-len(r)
        r = np.pad(r, (shape_refined,0), 'constant')
        #print(r)        

      len(reviews_ints[i])  

      features.append(r)


    
    features=np.array(features)
    
    return features

In [111]:
seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
print(len(features[0]))
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:10])

200
[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [31153    41 72394    15   688 17020  3354    47    78    35]
 [ 4886   504    15     3  3075   162  9246  1845     6  5074]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   52    10    14   114    60   756   554    70   368     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   333   575    34     3   162   770  2701     9   326]
 [    9    11 10071  5560  1967   704   445    22   292   681]
 [    0     0     0     0     0     0     0     0  

In [112]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		(2500, 200)


In [113]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
print(train_x.shape[0])
print(train_y.shape[0])

train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 50

# make sure to SHUFFLE your data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

20000
20000


In [114]:
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 200])
Sample input: 
 tensor([[    0,     0,     0,  ...,   458,     2,   378],
        [    1,  1026,   234,  ..., 10181,    22,     1],
        [   10,    28,   294,  ...,    33,    31,    28],
        ...,
        [    0,     0,     0,  ...,     1,   680,  1833],
        [    0,     0,     0,  ...,     4,    67,   599],
        [19519,    37,    11,  ...,     6,  1261,    16]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 0])
